# Pandas DataFrame

A **Pandas DataFrame** is a **two-dimensional, tabular data structure** in Python, similar to a **spreadsheet or SQL table**.

It contains **rows and columns**, where each column can represent a different **feature or variable**.

# import lobrary

In [50]:
import pandas as pd

# Empty Dataframe

In [51]:
df = pd.DataFrame()

In [52]:
df

Empty DataFrame
Columns: []
Index: []

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame

#### To work with a Pandas DataFrame, we need data. We can get the data from a list, dictionary, CSV or Excel file, or from anywhere else.

# List to DataFrame

In [54]:
city = ['Chittagong', 'Dhaka', 'Barishal']

In [55]:
df = pd.DataFrame(city)

In [56]:
df

            0
0  Chittagong
1       Dhaka
2    Barishal

In [57]:
type(df)

pandas.core.frame.DataFrame

In [58]:
type(city)

list

In [59]:
row, col = df.shape

In [60]:
row

3

In [61]:
col

1

In [62]:
  df.shape

(3, 1)

In [63]:
df = pd.DataFrame(city, columns = ['city_of_bd'], index = ['c1', 'c2', 'c3'])

In [64]:
df

    city_of_bd
c1  Chittagong
c2       Dhaka
c3    Barishal

# Work with two lists

In [65]:
city2 = ['Cumilla', 'Barishal', 'Khulna']

In [66]:
df2 = pd.DataFrame(zip(city, city2), columns = ['city1', 'city2'])

In [67]:
df2

        city1     city2
0  Chittagong   Cumilla
1       Dhaka  Barishal
2    Barishal    Khulna

In [68]:
df.shape

(3, 1)

In [69]:
df2.shape

(3, 2)

In [70]:
city3 = [['Dhaka', 'Chittagong', 'Khulna', 'Sylhet'], ['Barishal', 'Rajshahi', 'Mymensingh', 'Rangpur']]

In [71]:
df4 = pd.DataFrame(city3, columns = ['city1', 'city2', 'city3', 'city4'])

In [72]:
df4

      city1       city2       city3    city4
0     Dhaka  Chittagong      Khulna   Sylhet
1  Barishal    Rajshahi  Mymensingh  Rangpur

# Dictionary to DataFrame

In [73]:
city

['Chittagong', 'Dhaka', 'Barishal']

##

In [74]:
city2

['Cumilla', 'Barishal', 'Khulna']

In [75]:
 dict1 = {
     'city1': city,
     'city2': city2
 }

In [76]:
dict1

{'city1': ['Chittagong', 'Dhaka', 'Barishal'],
 'city2': ['Cumilla', 'Barishal', 'Khulna']}

In [77]:
df5 = pd.DataFrame(dict1)

In [78]:
df5

        city1     city2
0  Chittagong   Cumilla
1       Dhaka  Barishal
2    Barishal    Khulna

In [79]:
type(dict1)

dict