# Pandas DataFrame

## Import Library

## Convert 1D list to DataFrame

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame()

In [4]:
df

Empty DataFrame
Columns: []
Index: []

In [5]:
df.info

<bound method DataFrame.info of Empty DataFrame
Columns: []
Index: []>

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame

In [7]:
city = ['Chittagong', 'Dhaka', 'Khulna']

In [8]:
city

['Chittagong', 'Dhaka', 'Khulna']

In [9]:
df = pd.DataFrame(city)

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df

            0
0  Chittagong
1       Dhaka
2      Khulna

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes

In [13]:
df.info

<bound method DataFrame.info of             0
0  Chittagong
1       Dhaka
2      Khulna>

In [14]:
type(city)

list

In [28]:
row, col = df.shape

In [29]:
row

3

In [30]:
col

1

In [32]:
df.shape

(3, 1)

In [33]:
df

            0
0  Chittagong
1       Dhaka
2      Khulna

## Set Row & Column name

In [34]:
df = pd.DataFrame(city, column = ['Bangladesh'])

TypeError: DataFrame.__init__() got an unexpected keyword argument 'column'

In [35]:
df = pd.DataFrame(city, columns = ['Bangladesh'])

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Bangladesh  3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes

In [37]:
df.info

<bound method DataFrame.info of    Bangladesh
0  Chittagong
1       Dhaka
2      Khulna>

In [38]:
df

   Bangladesh
0  Chittagong
1       Dhaka
2      Khulna

In [39]:
df = pd.DataFrame(city, columns = ['Bangladesh'], index = ['C1', 'C2', 'C3'])

In [40]:
df

    Bangladesh
C1  Chittagong
C2       Dhaka
C3      Khulna

In [41]:
city2 = ['Rajshahi', 'Comilla', 'Barishal']

In [43]:
df = pd.DataFrame(zip(city, city2), columns = ['City1', 'City2'])

In [44]:
df

        City1     City2
0  Chittagong  Rajshahi
1       Dhaka   Comilla
2      Khulna  Barishal

In [45]:
df = pd.DataFrame(zip(city, city2), columns = ['City1', 'City2'], index = ['C1', 'C2', 'C3'])

In [46]:
df

         City1     City2
C1  Chittagong  Rajshahi
C2       Dhaka   Comilla
C3      Khulna  Barishal

In [47]:
df.shape

(3, 2)

## Convert 2D list to DataFrame

In [59]:
city3 = [['Bangladesh', 'Dhaka', 'Chittagong'], ['Russia', 'Moscow', 'Novosibirsk'], ['UK', 'London', 'Birmingham']]

In [60]:
city3

[['Bangladesh', 'Dhaka', 'Chittagong'],
 ['Russia', 'Moscow', 'Novosibirsk'],
 ['UK', 'London', 'Birmingham']]

In [61]:
df2 = pd.DataFrame(city3)

In [62]:
df2

            0       1            2
0  Bangladesh   Dhaka   Chittagong
1      Russia  Moscow  Novosibirsk
2          UK  London   Birmingham

In [65]:
df2 = pd.DataFrame(city3, columns = ['STATE', 'CITY_1', 'CITY_2'])

In [66]:
df2

        STATE  CITY_1       CITY_2
0  Bangladesh   Dhaka   Chittagong
1      Russia  Moscow  Novosibirsk
2          UK  London   Birmingham

In [71]:
df2 = pd.DataFrame(city3, columns = ['STATE', 'CITY_1', 'CITY_2'], index = ['1', '2', '3'])

In [72]:
df2

        STATE  CITY_1       CITY_2
1  Bangladesh   Dhaka   Chittagong
2      Russia  Moscow  Novosibirsk
3          UK  London   Birmingham

In [74]:
city

['Chittagong', 'Dhaka', 'Khulna']

In [75]:
city2

['Rajshahi', 'Comilla', 'Barishal']

# Dictionary to DataFrame

In [80]:
dict1 = {
    'City_1': city,
    'City_2': city2
}

In [81]:
dict1

{'City_1': ['Chittagong', 'Dhaka', 'Khulna'],
 'City_2': ['Rajshahi', 'Comilla', 'Barishal']}

In [82]:
df3 = pd.DataFrame(dict1)

In [83]:
df3

       City_1    City_2
0  Chittagong  Rajshahi
1       Dhaka   Comilla
2      Khulna  Barishal

In [84]:
df3 = pd.DataFrame(dict1, index = ['1', '2', '3'])

In [85]:
df3

       City_1    City_2
1  Chittagong  Rajshahi
2       Dhaka   Comilla
3      Khulna  Barishal

In [88]:
type(dict1)

dict

In [89]:
city7 = [['Bangladesh', 'Comilla', 'Barishal'], ['Russia', 'Petersburg', 'Samara'], ['UK', 'Mancheste', 'Plymouth']]

In [90]:
city3

[['Bangladesh', 'Dhaka', 'Chittagong'],
 ['Russia', 'Moscow', 'Novosibirsk'],
 ['UK', 'London', 'Birmingham']]

In [91]:
dict2 = {
    'City_7': city3,
    'City_8': city7
}

In [92]:
dict2

{'City_7': [['Bangladesh', 'Dhaka', 'Chittagong'],
  ['Russia', 'Moscow', 'Novosibirsk'],
  ['UK', 'London', 'Birmingham']],
 'City_8': [['Bangladesh', 'Comilla', 'Barishal'],
  ['Russia', 'Petersburg', 'Samara'],
  ['UK', 'Mancheste', 'Plymouth']]}

In [93]:
df8 = pd.DataFrame(dict2)

In [95]:
df8

                            City_7                           City_8
0  [Bangladesh, Dhaka, Chittagong]  [Bangladesh, Comilla, Barishal]
1    [Russia, Moscow, Novosibirsk]     [Russia, Petersburg, Samara]
2         [UK, London, Birmingham]        [UK, Mancheste, Plymouth]

In [96]:
df8.shape

(3, 2)